unit DefDio;

interface

{$I Common.inc}

const

  // DAE DIO 사용.
{$IFDEF INSPECTOR_OC}
  MAX_IO_CNT = 96;
  MAX_IN_CNT = 96;
  MAX_OUT_CNT = 96;
{$ELSE}
  MAX_IO_CNT = 64;
  MAX_IN_CNT = 64;
  MAX_OUT_CNT = 64;
{$ENDIF}


  DAE_IO_DEVICE_IP = '192.168.0.99';
  DAE_IO_DEVICE_PORT = 6989;
  DAE_IO_DEVICE_INTERVAL = 200;

{$IFDEF INSPECTOR_OC}
  DAE_IO_DEVICE_COUNT = 12;
{$ELSE}
  DAE_IO_DEVICE_COUNT = 8;
{$ENDIF}


  TYPE_NORMAL = 0;
  TYPE_GIB = 1;

  ALL_CH = 0;
  TOP_CH = 1;
  BOTTOM_CH = 2;

  // for 128 channel Items.
  // IN SIGNAL.

  IN_FAN_1_EXHAUST = 0; // FAN 1 신호 구동 High -> 정지 Low
  IN_FAN_2_INTAKE = 1; // FAN 2 신호 구동 High -> 정지 Low
  IN_FAN_3_EXHAUST = 2; // FAN 3 신호 구동 High -> 정지 Low
  IN_FAN_4_INTAKE = 3; // FAN 4 신호 구동 High -> 정지 Low
  IN_UNDEFINED_4 = 4;
  IN_UNDEFINED_5 = 5;
  IN_UNDEFINED_6 = 6;
  IN_UNDEFINED_7 = 7;

  IN_EMO_SWITCH = 8; // EMO OFF 시 High -> 해제 Low
  IN_CH_1_2_DOOR_LEFT_OPEN = 9; // OPEN 시 Low → Close시 High
  IN_CH_1_2_DOOR_RIGHT_OPEN = 10; // OPEN 시 Low → Close시 High
  IN_CH_3_4_DOOR_LEFT_OPEN = 11; // OPEN 시 Low → Close시 High
  IN_CH_3_4_DOOR_RIGHT_OPEN = 12; // OPEN 시 Low → Close시 High
  IN_MC_MONITORING = 13; // High -> EMO, Door 감지 시 Low
  IN_UNDEFINED_14 = 14;
  IN_UNDEFINED_15 = 15;

  IN_TEMPERATURE_ALARM = 16; // 40' 감지 시 High
  IN_UNDEFINED_17 = 17;
  IN_UNDEFINED_18 = 18;
  IN_UNDEFINED_19 = 19;
  IN_UNDEFINED_20 = 20;
  IN_UNDEFINED_21 = 21;
  IN_UNDEFINED_22 = 22;
  IN_UNDEFINED_23 = 23;

  IN_CYL_PRESSURE_GAUGE = 24; // CYL PRESSURE GAUGE
  IN_UNDEFINED_25 = 25;
  IN_UNDEFINED_26 = 26;
  IN_UNDEFINED_27 = 27;
  IN_UNDEFINED_28 = 28;
  IN_UNDEFINED_29 = 29;
  IN_UNDEFINED_30 = 30;
  IN_UNDEFINED_31 = 31;

  IN_CH_1_CARRIER_SENSOR = 32;
  IN_CH_1_PROBE_FORWARD_SENSOR = 33;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_1_PROBE_BACKWARD_SENSOR = 34;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_1_PROBE_UP_SENSOR = 35;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_1_PROBE_DOWN_SENSOR = 36;  //SEN 감지 시 Low -> 비감지 시 High
  IN_UNDEFINED_37 = 37;
  IN_UNDEFINED_38 = 38;
  IN_UNDEFINED_39 = 39;

  IN_CH_1_CARRIER_UNLOCK_SENSOR_1 = 40;
  IN_CH_1_CARRIER_LOCK_1          = 41;
  IN_CH_1_CARRIER_UNLOCK_SENSOR_2 = 42;
  IN_CH_1_CARRIER_LOCK_2          = 43;
  IN_CH_1_CARRIER_UNLOCK_SENSOR_3 = 44;
  IN_CH_1_CARRIER_LOCK_3          = 45;
  IN_CH_1_CARRIER_UNLOCK_SENSOR_4 = 46;
  IN_CH_1_CARRIER_LOCK_4          = 47;

//  IN_UNDEFINED_48 = 48;
//  IN_UNDEFINED_49 = 49;
//  IN_UNDEFINED_50 = 50;
//  IN_UNDEFINED_51 = 51;
//  IN_UNDEFINED_52 = 52;
//  IN_UNDEFINED_53 = 53;
//  IN_UNDEFINED_54 = 54;
//  IN_UNDEFINED_55 = 55;

  IN_CH_2_CARRIER_SENSOR = 48;
  IN_CH_2_PROBE_FORWARD_SENSOR = 49;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_2_PROBE_BACKWARD_SENSOR = 50;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_2_PROBE_UP_SENSOR = 51;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_2_PROBE_DOWN_SENSOR = 52;  //SEN 감지 시 Low -> 비감지 시 High
  IN_UNDEFINED_61 = 53;
  IN_UNDEFINED_62 = 54;
  IN_UNDEFINED_63 = 55;

  IN_CH_2_CARRIER_UNLOCK_SENSOR_1 = 56;
  IN_CH_2_CARRIER_LOCK_1          = 57;
  IN_CH_2_CARRIER_UNLOCK_SENSOR_2 = 58;
  IN_CH_2_CARRIER_LOCK_2          = 59;
  IN_CH_2_CARRIER_UNLOCK_SENSOR_3 = 60;
  IN_CH_2_CARRIER_LOCK_3          = 61;
  IN_CH_2_CARRIER_UNLOCK_SENSOR_4 = 62;
  IN_CH_2_CARRIER_LOCK_4          = 63;

//  IN_UNDEFINED_72 = 72;
//  IN_UNDEFINED_73 = 73;
//  IN_UNDEFINED_74 = 74;
//  IN_UNDEFINED_75 = 75;
//  IN_UNDEFINED_76 = 76;
//  IN_UNDEFINED_77 = 77;
//  IN_UNDEFINED_78 = 78;
//  IN_UNDEFINED_79 = 79;

  IN_CH_3_CARRIER_SENSOR = 64;
  IN_CH_3_PROBE_FORWARD_SENSOR = 65;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_3_PROBE_BACKWARD_SENSOR = 66;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_3_PROBE_UP_SENSOR = 67;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_3_PROBE_DOWN_SENSOR = 68;  //SEN 감지 시 Low -> 비감지 시 High
  IN_UNDEFINED_85 = 69;
  IN_UNDEFINED_86 = 70;
  IN_UNDEFINED_87 = 71;

  IN_CH_3_CARRIER_UNLOCK_SENSOR_1 = 72;
  IN_CH_3_CARRIER_LOCK_1          = 73;
  IN_CH_3_CARRIER_UNLOCK_SENSOR_2 = 74;
  IN_CH_3_CARRIER_LOCK_2          = 75;
  IN_CH_3_CARRIER_UNLOCK_SENSOR_3 = 76;
  IN_CH_3_CARRIER_LOCK_3          = 77;
  IN_CH_3_CARRIER_UNLOCK_SENSOR_4 = 78;
  IN_CH_3_CARRIER_LOCK_4          = 79;

//  IN_UNDEFINED_96 = 96;
//  IN_UNDEFINED_97 = 97;
//  IN_UNDEFINED_98 = 98;
//  IN_UNDEFINED_99 = 99;
//  IN_UNDEFINED_100 = 100;
//  IN_UNDEFINED_101 = 101;
//  IN_UNDEFINED_102 = 102;
//  IN_UNDEFINED_103 = 103;

  IN_CH_4_CARRIER_SENSOR = 80;
  IN_CH_4_PROBE_FORWARD_SENSOR = 81;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_4_PROBE_BACKWARD_SENSOR = 82;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_4_PROBE_UP_SENSOR = 83;  //SEN 감지 시 Low -> 비감지 시 High
  IN_CH_4_PROBE_DOWN_SENSOR = 84;  //SEN 감지 시 Low -> 비감지 시 High
  IN_UNDEFINED_109 = 85;
  IN_UNDEFINED_110 = 86;
  IN_UNDEFINED_111 = 87;

  IN_CH_4_CARRIER_UNLOCK_SENSOR_1 = 88;
  IN_CH_4_CARRIER_LOCK_1          = 89;
  IN_CH_4_CARRIER_UNLOCK_SENSOR_2 = 90;
  IN_CH_4_CARRIER_LOCK_2          = 91;
  IN_CH_4_CARRIER_UNLOCK_SENSOR_3 = 92;
  IN_CH_4_CARRIER_LOCK_3          = 93;
  IN_CH_4_CARRIER_UNLOCK_SENSOR_4 = 94;
  IN_CH_4_CARRIER_LOCK_4          = 95;

//  IN_UNDEFINED_120 = 120;
//  IN_UNDEFINED_121 = 121;
//  IN_UNDEFINED_122 = 122;
//  IN_UNDEFINED_123 = 123;
//  IN_UNDEFINED_124 = 124;
//  IN_UNDEFINED_125 = 125;
//  IN_UNDEFINED_126 = 126;
//  IN_UNDEFINED_127 = 127;

  IN_MAX = IN_CH_4_CARRIER_LOCK_4;

  // IN SIGNAL.
  OUT_CH_1_2_LAMP_OFF = 0;
  OUT_CH_3_4_LAMP_OFF = 1;
  OUT_CH_1_PG_POWER_OFF = 2;
  OUT_CH_2_PG_POWER_OFF = 3;
  OUT_CH_3_PG_POWER_OFF = 4;
  OUT_CH_4_PG_POWER_OFF = 5;
  OUT_UNDEFINED_6 = 6;
  OUT_START_SW_LED = 7;

  OUT_CH_1_2_DOOR_LEFT_UNLOCK = 8;
  OUT_CH_1_2_DOOR_RIGHT_UNLOCK = 9;
  OUT_CH_3_4_DOOR_LEFT_UNLOCK = 10;
  OUT_CH_3_4_DOOR_RIGHT_UNLOCK = 11;
  OUT_RESET_SWITCH_LED = 12;
  OUT_UNDEFINED_13 = 13;
  OUT_UNDEFINED_14 = 14;
  OUT_UNDEFINED_15 = 15;

  OUT_TOWER_LAMP_RED = 16;
  OUT_TOWER_LAMP_YELLOW = 17;
  OUT_TOWER_LAMP_GREEN = 18;
  OUT_BUZZER_1 = 19;
  OUT_BUZZER_2 = 20;
  OUT_BUZZER_3 = 21;
  OUT_BUZZER_4 = 22;
  OUT_UNDEFINED_23 = 23;

  OUT_CH_1_2_ION_ONOFF_SOL = 24;
  OUT_CH_3_4_ION_ONOFF_SOL = 25;
  OUT_CH_1_2_BACK_DOOR_LAMPON = 26;
  OUT_CH_3_4_BACK_DOOR_LAMPON = 27;
  OUT_UNDEFINED_28 = 28;
  OUT_UNDEFINED_29 = 29;
  OUT_UNDEFINED_30 = 30;
  OUT_UNDEFINED_31 = 31;

  OUT_CH_1_PROBE_FORWARD_SOL  = 32;
  OUT_CH_1_PROBE_BACKWARD_SOL = 33;
  OUT_CH_1_PROBE_UP_SOL       = 34;
  OUT_CH_1_PROBE_DOWN_SOL     = 35;
  OUT_CH_1_CARRIER_UNLOCK_SOL = 36;
  OUT_CH_1_CARRIER_LOCK_SOL = 37;
  OUT_UNDEFINED_36 = 38;
  OUT_UNDEFINED_37 = 39;

  OUT_UNDEFINED_40 = 40;
  OUT_UNDEFINED_41 = 41;
  OUT_UNDEFINED_42 = 42;
  OUT_UNDEFINED_43 = 43;
  OUT_UNDEFINED_44 = 44;
  OUT_UNDEFINED_45 = 45;
  OUT_UNDEFINED_46 = 46;
  OUT_UNDEFINED_47 = 47;

//  OUT_UNDEFINED_48 = 48;
//  OUT_UNDEFINED_49 = 49;
//  OUT_UNDEFINED_50 = 50;
//  OUT_UNDEFINED_51 = 51;
//  OUT_UNDEFINED_52 = 52;
//  OUT_UNDEFINED_53 = 53;
//  OUT_UNDEFINED_38 = 54;
//  OUT_UNDEFINED_39 = 55;

  OUT_CH_2_PROBE_FORWARD_SOL = 48;
  OUT_CH_2_PROBE_BACKWARD_SOL = 49;
  OUT_CH_2_PROBE_UP_SOL = 50;
  OUT_CH_2_PROBE_DOWN_SOL = 51;
  OUT_CH_2_CARRIER_UNLOCK_SOL = 52;
  OUT_CH_2_CARRIER_LOCK_SOL = 53;
  OUT_UNDEFINED_62 = 54;
  OUT_UNDEFINED_63 = 55;

  OUT_UNDEFINED_64 = 56;
  OUT_UNDEFINED_65 = 57;
  OUT_UNDEFINED_66 = 58;
  OUT_UNDEFINED_67 = 59;
  OUT_UNDEFINED_68 = 60;
  OUT_UNDEFINED_69 = 61;
  OUT_UNDEFINED_70 = 62;
  OUT_UNDEFINED_71 = 63;

//  OUT_UNDEFINED_72 = 72;
//  OUT_UNDEFINED_73 = 73;
//  OUT_UNDEFINED_74 = 74;
//  OUT_UNDEFINED_75 = 75;
//  OUT_UNDEFINED_76 = 76;
//  OUT_UNDEFINED_77 = 77;
//  OUT_UNDEFINED_78 = 78;
//  OUT_UNDEFINED_79 = 79;

  OUT_CH_3_PROBE_FORWARD_SOL = 64;
  OUT_CH_3_PROBE_BACKWARD_SOL = 65;
  OUT_CH_3_PROBE_UP_SOL = 66;
  OUT_CH_3_PROBE_DOWN_SOL = 67;
  OUT_CH_3_CARRIER_UNLOCK_SOL = 68;
  OUT_CH_3_CARRIER_LOCK_SOL = 69;
  OUT_UNDEFINED_86 = 70;
  OUT_UNDEFINED_87 = 71;

  OUT_UNDEFINED_88 = 72;
  OUT_UNDEFINED_89 = 73;
  OUT_UNDEFINED_90 = 74;
  OUT_UNDEFINED_91 = 75;
  OUT_UNDEFINED_92 = 76;
  OUT_UNDEFINED_93 = 77;
  OUT_UNDEFINED_94 = 78;
  OUT_UNDEFINED_95 = 79;

//  OUT_UNDEFINED_96 = 96;
//  OUT_UNDEFINED_97 = 97;
//  OUT_UNDEFINED_98 = 98;
//  OUT_UNDEFINED_99 = 99;
//  OUT_UNDEFINED_100 = 100;
//  OUT_UNDEFINED_101 = 101;
//  OUT_UNDEFINED_102 = 102;
//  OUT_UNDEFINED_103 = 103;

  OUT_CH_4_PROBE_FORWARD_SOL = 80;
  OUT_CH_4_PROBE_BACKWARD_SOL = 81;
  OUT_CH_4_PROBE_UP_SOL = 82;
  OUT_CH_4_PROBE_DOWN_SOL = 83;
  OUT_CH_4_CARRIER_UNLOCK_SOL = 84;
  OUT_CH_4_CARRIER_LOCK_SOL = 85;
  OUT_UNDEFINED_110 = 86;
  OUT_UNDEFINED_111 = 87;

  OUT_UNDEFINED_112 = 88;
  OUT_UNDEFINED_113 = 89;
  OUT_UNDEFINED_114 = 90;
  OUT_UNDEFINED_115 = 91;
  OUT_UNDEFINED_116 = 92;
  OUT_UNDEFINED_117 = 93;
  OUT_UNDEFINED_118 = 94;
  OUT_UNDEFINED_119 = 95;

//  OUT_UNDEFINED_120 = 120;
//  OUT_UNDEFINED_121 = 121;
//  OUT_UNDEFINED_122 = 122;
//  OUT_UNDEFINED_123 = 123;
//  OUT_UNDEFINED_124 = 124;
//  OUT_UNDEFINED_125 = 125;
//  OUT_UNDEFINED_126 = 126;
//  OUT_UNDEFINED_127 = 127;

  OUT_MAX = OUT_UNDEFINED_119;


  // Pre_OC  IN SIGNAL.


  IN_GIB_CH_12_EMO_SWITCH     = 4;
  IN_GIB_CH_34_EMO_SWITCH     = 5;
  IN_GIB_CH_12_LIGHTCURTAIN     = 6;
  IN_GIB_CH_34_LIGHTCURTAIN     = 7;

  IN_GIB_CH_12_MUTING_LAMP    = 8;
  IN_GIB_CH_34_MUTING_LAMP    = 9;
  IN_GIB_CH_12_MC_MONITORING  = 10;
  IN_GIB_CH_34_MC_MONITORING  = 11;
  IN_GIB_TEMPERATURE_ALARM    = 12;

  IN_GIB_CYL_PRESSURE_GAUGE =16;

  IN_GIB_CH_1_CARRIER_SENSOR                = 24;
  IN_GIB_CH_1_TILTING_SENSOR                = 25;
  IN_GIB_CH_1_PINBLOCK_OPEN_SENSOR          = 26;
  IN_GIB_CH_1_PRESSURE_GUAGE                = 27;
  IN_GIB_CH_1_PINBLOCK_UNLOCK_OF_SENSOR     = 28;
  IN_GIB_CH_1_PINBLOCK_UNLOCK_ON_SENSOR     = 29;
  IN_GIB_CH_1_PINBLOCK_CLOSE_UP_SENSOR      = 30;
  IN_GIB_CH_1_PINBLOCK_CLOSE_DN_SENSOR      = 31;


  IN_GIB_CH_2_CARRIER_SENSOR                   = 32;
  IN_GIB_CH_2_TILTING_SENSOR                   = 33;
  IN_GIB_CH_2_PINBLOCK_OPEN_SENSOR             = 34;
  IN_GIB_CH_2_PRESSURE_GUAGE                   = 35;
  IN_GIB_CH_2_PINBLOCK_UNLOCK_OF_SENSOR        = 36;
  IN_GIB_CH_2_PINBLOCK_UNLOCK_ON_SENSOR        = 37;
  IN_GIB_CH_2_PINBLOCK_CLOSE_UP_SENSOR         = 38;
  IN_GIB_CH_2_PINBLOCK_CLOSE_DN_SENSOR        = 39;

  IN_GIB_CH_3_CARRIER_SENSOR                   = 40;
  IN_GIB_CH_3_TILTING_SENSOR                   = 41;
  IN_GIB_CH_3_PINBLOCK_OPEN_SENSOR             = 42;
  IN_GIB_CH_3_PRESSURE_GUAGE                   = 43;
  IN_GIB_CH_3_PINBLOCK_UNLOCK_OF_SENSOR        = 44;
  IN_GIB_CH_3_PINBLOCK_UNLOCK_ON_SENSOR        = 45;
  IN_GIB_CH_3_PINBLOCK_CLOSE_UP_SENSOR         = 46;
  IN_GIB_CH_3_PINBLOCK_CLOSE_DN_SENSOR        = 47;

  IN_GIB_CH_4_CARRIER_SENSOR                   = 48;
  IN_GIB_CH_4_TILTING_SENSOR                   = 49;
  IN_GIB_CH_4_PINBLOCK_OPEN_SENSOR             = 50;
  IN_GIB_CH_4_PRESSURE_GUAGE                   = 51;
  IN_GIB_CH_4_PINBLOCK_UNLOCK_OF_SENSOR        = 52;
  IN_GIB_CH_4_PINBLOCK_UNLOCK_ON_SENSOR        = 53;
  IN_GIB_CH_4_PINBLOCK_CLOSE_UP_SENSOR         = 54;
  IN_GIB_CH_4_PINBLOCK_CLOSE_DN_SENSOR        = 55;

  IN_GIB_CH_12_PROBE_UP_SENSOR          = 56;
  IN_GIB_CH_12_PROBE_DN_SENSOR        = 57;
  IN_GIB_CH_12_SHUTTER_UP_SENSOR        = 58;
  IN_GIB_CH_12_SHUTTER_DN_SENSOR      = 59;
  IN_GIB_CH_34_PROBE_UP_SENSOR          = 60;
  IN_GIB_CH_34_PROBE_DN_SENSOR        = 61;
  IN_GIB_CH_34_SHUTTER_UP_SENSOR        = 62;
  IN_GIB_CH_34_SHUTTER_DN_SENSOR      = 63;


    // Pre_OC  OUT SIGNAL.
  OUT_CH_12_RESET_SWTCH_LED = 6;
  OUT_CH_34_RESET_SWTCH_LED = 7;

  OUT_GIB_TOWER_LAMP_RED    = 8;
  OUT_GIB_TOWER_LAMP_YELLOW = 9;
  OUT_GIB_TOWER_LAMP_GREEN  = 10;
  OUT_GIB_BUZZER_1          = 11;
  OUT_GIB_BUZZER_2          = 12;
  OUT_GIB_BUZZER_3          = 13;
  OUT_GIB_BUZZER_4          = 14;

  OUT_GIB_CH_12_ION_ONOFF_SOL = 16;
  OUT_GIB_CH_34_ION_ONOFF_SOL = 17;


  OUT_GIB_CH_1_VACCUM_SOL          = 24;
  OUT_GIB_CH_1_PINBLOCK_UNLOCK_SOL = 25;
  OUT_GIB_CH_1_PINBLOCK_CLOSE_SOL  = 26;

  OUT_GIB_CH_2_VACCUM_SOL          = 32;
  OUT_GIB_CH_2_PINBLOCK_UNLOCK_SOL = 33;
  OUT_GIB_CH_2_PINBLOCK_CLOSE_SOL  = 34;

  OUT_GIB_CH_3_VACCUM_SOL          = 40;
  OUT_GIB_CH_3_PINBLOCK_UNLOCK_SOL = 41;
  OUT_GIB_CH_3_PINBLOCK_CLOSE_SOL  = 42;

  OUT_GIB_CH_4_VACCUM_SOL          = 48;
  OUT_GIB_CH_4_PINBLOCK_UNLOCK_SOL = 49;
  OUT_GIB_CH_4_PINBLOCK_CLOSE_SOL  = 50;

  OUT_GIB_CH_12_PROBE_UP_SOL          = 56;
  OUT_GIB_CH_12_PROBE_DN_SOL        = 57;
  OUT_GIB_CH_12_SHUTTER_UP_SOL        = 58;
  OUT_GIB_CH_12_SHUTTER_DN_SOL      = 59;
  OUT_GIB_CH_34_PROBE_UP_SOL          = 60;
  OUT_GIB_CH_34_PROBE_DN_SOL        = 61;
  OUT_GIB_CH_34_SHUTTER_UP_SOL        = 62;
  OUT_GIB_CH_34_SHUTTER_DN_SOL      = 63;



 {
             // for 64 channel Items.
    // IN SIGNAL.
    IN_START_SW               = 0;
    IN_FRONT_EMS              = 1;
    IN_SIDE_EMS               = 2;
    IN_RIGHT_INNER_EMS        = 3;
    IN_LEFT_INNER_EMS         = 4;
    IN_REAR_EMS               = 5;
    IN_FAN1_IN                = 6;
    IN_FAN2_IN                = 7;
    IN_FAN3_OUT               = 8;
    IN_FAN4_OUT               = 9;
    IN_FAN5_IN                = 10;
    IN_FAN6_IN                = 11;
    IN_FAN7_OUT               = 12;
    IN_FAN8_OUT               = 13;
    IN_MOVING_AIR_REGULATOR   = 14;
    IN_Z_XIS_MOTOR_OUT1       = 15;

    IN_TEMPERTURE_ALARM       = 16;
    IN_POWER_HIGH_ALARM       = 17;
    IN_LIGHT_CURTAIN          = 18;
    IN_AUTO_MODE_SEL_KEY      = 19;
    IN_TEACH_MODE_SEL_KEY     = 20;
    IN_UPPER_LEFT_DOOR        = 21;
    IN_UPPER_RIGHT_DOOR       = 22;
    IN_LOWER_LEFT_DOOR        = 23;
    IN_LOWER_RIGHT_DOOR       = 24;
    //IN_MC_MONITORING          = 25;
    IN_B_STAGE_IN_CAM         = 26;
    IN_A_STAGE_IN_CAM         = 27;
    IN_MORTOR_STOP_SENSOR     = 28;
    IN_SHUTTER_UP_SENSOR      = 29;
    IN_SHUTTER_DN_SNENSOR     = 30;

    IN_CLAMP_UP_SENSOR_1CH_1  = 32;
    IN_CLAMP_UP_SENSOR_1CH_2  = 33;
    IN_POGO_DN_SENSOR_1CH     = 34;
    IN_DETECTION_SENSOR_1CH   = 35;

//    DIO_IN_CLAMP_UP_SENSOR_2CH_1  = 36;
//    DIO_IN_CLAMP_UP_SENSOR_2CH_2  = 37;
//    DIO_IN_POGO_DN_SENSOR_2CH     = 38;
//    DIO_IN_DETECTION_SENSOR_2CH   = 39;
//
//    DIO_IN_CLAMP_UP_SENSOR_3CH_1  = 40;
//    DIO_IN_CLAMP_UP_SENSOR_3CH_2  = 41;
//    DIO_IN_POGO_DN_SENSOR_3CH     = 42;
//    DIO_IN_DETECTION_SENSOR_3CH   = 43;
//
//    DIO_IN_CLAMP_UP_SENSOR_4CH_1  = 44;
//    DIO_IN_CLAMP_UP_SENSOR_4CH_2  = 45;
//    DIO_IN_POGO_DN_SENSOR_4CH     = 46;
//    DIO_IN_DETECTION_SENSOR_4CH   = 47;
//
//    DIO_IN_CLAMP_UP_SENSOR_5CH_1  = 48;
//    DIO_IN_CLAMP_UP_SENSOR_5CH_2  = 49;
//    DIO_IN_POGO_DN_SENSOR_5CH     = 50;
//    DIO_IN_DETECTION_SENSOR_5CH   = 51;
//
//    DIO_IN_CLAMP_UP_SENSOR_6CH_1  = 52;
//    DIO_IN_CLAMP_UP_SENSOR_6CH_2  = 53;
//    DIO_IN_POGO_DN_SENSOR_6CH     = 54;
//    DIO_IN_DETECTION_SENSOR_6CH   = 55;
//
//    DIO_IN_CLAMP_UP_SENSOR_7CH_1  = 56;
//    DIO_IN_CLAMP_UP_SENSOR_7CH_2  = 57;
//    DIO_IN_POGO_DN_SENSOR_7CH     = 58;
//    DIO_IN_DETECTION_SENSOR_7CH   = 59;
//
//    DIO_IN_CLAMP_UP_SENSOR_8CH_1  = 60;
//    DIO_IN_CLAMP_UP_SENSOR_8CH_2  = 61;
//    DIO_IN_POGO_DN_SENSOR_8CH     = 62;
    IN_DETECTION_SENSOR_8CH   = 63;

    //IN_MAX = IN_DETECTION_SENSOR_8CH;

    // For GIB
    IN_AIR_ISOLATOR_SENSOR1    = 64;
    IN_AIR_ISOLATOR_SENSOR2    = 65;
    IN_AIR_ISOLATOR_SENSOR3    = 66;
    IN_AIR_ISOLATOR_SENSOR4    = 67;
    IN_AIR_ISOLATOR_LEFT_DOOR  = 68;
    IN_AIR_ISOLATOR_RIGHT_DOOR = 69;

    // OUT SIGNAL.
    OUT_START_SW_LED          = 0;
    OUT_RESET_SW_LED          = 1;
    OUT_WORKER_LAMP           = 2;
    OUT_RED_LAMP              = 3;
    OUT_YELLOW_LAMP           = 4;
    OUT_GREEN_LAMP            = 5;
    OUT_MELODY_1              = 6;
    OUT_MELODY_2              = 7;
    OUT_MELODY_3              = 8;
    OUT_MELODY_4              = 9;
    OUT_Z_XIS_MOTOR_IN1       = 10;
    OUT_SIDE_SEL_KEY_UNLOCK     = 11;
    OUT_UPPER_LEFT_DOOR_UNLOCK  = 12;
    OUT_UPPER_RIGHT_DOOR_UNLOCK = 13;

    OUT_ION_BAR_SOL           = 14;
    OUT_AIR_KNIFE_SOL         = 15;
    OUT_A_STAGE_FRONT         = 16;
    OUT_B_STAGE_FRONT         = 17;
    OUT_SHUTTER_UP_SOL        = 18;
    OUT_SHUTTER_DN_SOL        = 19;

    OUT_CLAMP_UP_SOL_12CH     = 32;
    OUT_CLAMP_DN_SOL_12CH     = 33;
    OUT_POGO_UP_SOL_12CH      = 34;
    OUT_POGO_DN_SOL_12CH      = 35;

    OUT_CLAMP_UP_SOL_34CH     = 40;
    OUT_CLAMP_DN_SOL_34CH     = 41;
    OUT_POGO_UP_SOL_34CH      = 42;
    OUT_POGO_DN_SOL_34CH      = 43;

    OUT_CLAMP_UP_SOL_56CH     = 48;
    OUT_CLAMP_DN_SOL_56CH     = 49;
    OUT_POGO_UP_SOL_56CH      = 50;
    OUT_POGO_DN_SOL_56CH      = 51;

    OUT_CLAMP_UP_SOL_78CH     = 56;
    OUT_CLAMP_DN_SOL_78CH     = 57;
    OUT_POGO_UP_SOL_78CH      = 58;
    OUT_POGO_DN_SOL_78CH      = 59;

    //OUT_MAX = OUT_POGO_DN_SOL_78CH;
    }

  LAMP_STATE_NONE = 0;
  LAMP_STATE_MANUAL = LAMP_STATE_NONE + 1;
  LAMP_STATE_PAUSE = LAMP_STATE_NONE + 2;
  LAMP_STATE_AUTO = LAMP_STATE_NONE + 3;
  LAMP_STATE_REQUEST = LAMP_STATE_NONE + 4;
  LAMP_STATE_ERROR = LAMP_STATE_NONE + 5;
  LAMP_STATE_EMEGENCY = LAMP_STATE_NONE + 6;


  // Error list.

  // 1	FRONT EMS (DI01)
  // 2	SIDE EMS (DI02)
  // 3	RIGHT INNER EMS (DI03)
  // 4	LEFT INNER EMS (DI04)
  // 5	REAR EMS (DI05)
  // 6	LIGHT CURTAIN (DI18)
  // 7	UPPER LEFT DOOR (DI21)
  // 8	UPPER RIGHT DOOR (DI22)
  ERR_LIST_START = -1;
  ERR_LIST_FRONT_EMS = ERR_LIST_START + 1;
  ERR_LIST_SIDE_EMS = ERR_LIST_START + 2;
  ERR_LIST_R_INNER_EMS = ERR_LIST_START + 3;
  ERR_LIST_L_INNER_EMS = ERR_LIST_START + 4;
  ERR_LIST_REAR_EMS = ERR_LIST_START + 5;
  ERR_LIST_LIGHT_CUTAIN = ERR_LIST_START + 6;
  ERR_LIST_U_L_DOOR = ERR_LIST_START + 7;
  ERR_LIST_U_R_DOOR = ERR_LIST_START + 8;

  // 9	LOWER LEFT DOOR (DI23)
  // 10	LOWER RIGHT DOOR (DI24)
  // 11	FAN#1 흡기 (DI06)
  // 12	FAN#2 흡기 (DI07)
  // 13	FAN#3 배기 ((DI08)
  // 14	FAN#4 배기 (DI09)
  // 15	FAN#5 흡기 (DI10)

  ERR_LIST_L_L_DOOR = ERR_LIST_START + 9;
  ERR_LIST_L_R_DOOR = ERR_LIST_START + 10;
  ERR_LIST_FAN_1_OUT = ERR_LIST_START + 11;

  // 16	FAN#6 흡기 (DI11)
  // 17	FAN#7 배기 (DI12)
  // 18	FAN#8 배기 (DI13)
  // 19	Main AIR PRESSURE NG ((DI14)
  // 20	TEMPERATURE ALARM (DI16)
  // 21	POWER HIGH ALARM (DI17)
  // 22	Need to press Reset button(DI25)

  ERR_LIST_MAIN_AIR_PRESURE = ERR_LIST_START + 19;
  ERR_LIST_TEMPRERATURE = ERR_LIST_START + 20;
  ERR_LIST_POWER_HIGH = ERR_LIST_START + 21;
  ERR_LIST_MC_MONITOR = ERR_LIST_START + 22;

  // 23	A Stage Position NG(DI26)
  // 24	B Stage Position NG(DI27)
  // 25	Shutter up sensor NG(DI28)
  // 26	Shutter Down sensor NG(DI29)
  // 27	Clamp up sensor-1 1Ch NG(DI32)
  // 28	Clamp up sensor-1 2Ch NG(DI36)
  // 29	Clamp up sensor-1 3Ch NG(DI40)
  // 30	Clamp up sensor-1 4Ch NG(DI44)
  // 31	Clamp up sensor-1 5Ch NG(DI48)
  ERR_LIST_A_STAGE_SENSOR = ERR_LIST_START + 25;
  ERR_LIST_B_STAGE_SENSOR = ERR_LIST_START + 26;
  ERR_LIST_SHUTTER_UP_SENSOR = ERR_LIST_START + 27;
  ERR_LIST_SHUTTER_DN_SENSOR = ERR_LIST_START + 28;
  ERR_LIST_CAMP_UP_SENSOR_1 = ERR_LIST_START + 29;
  // 32	Clamp up sensor-1 6Ch NG(DI52)
  // 33	Clamp up sensor-1 7Ch NG(DI56)
  // 34	Clamp up sensor-1 8Ch NG(DI60)
  // 35	Clamp up sensor-2 1Ch NG(DI33)
  // 36	Clamp up sensor-2 2Ch NG(DI37)
  // 37	Clamp up sensor-2 3Ch NG(DI41)
  // 38	Clamp up sensor-2 4Ch NG(DI45)
  // 39	Clamp up sensor-2 5Ch NG(DI49)
  ERR_LIST_CAMP_UP_SENSOR_2 = ERR_LIST_START + 37;
  // 40	Clamp up sensor-2 6Ch NG(DI53)
  // 41	Clamp up sensor-2 7Ch NG(DI57)
  // 42	Clamp up sensor-2 8Ch NG(DI61)
  // 43	Clamp down sensor-1 1Ch NG(DI32)
  // 44	Clamp down sensor-1 2Ch NG(DI36)
  // 45	Clamp down sensor-1 3Ch NG(DI40)
  // 46	Clamp down sensor-1 4Ch NG(DI44)
  // 47	Clamp down sensor-1 5Ch NG(DI48)
  ERR_LIST_CAMP_DN_SENSOR_1 = ERR_LIST_START + 45;
  // 48	Clamp down sensor-1 6Ch NG(DI52)
  // 49	Clamp down sensor-1 7Ch NG(DI56)
  // 50	Clamp down sensor-1 8Ch NG(DI60)
  // 51	Clamp down sensor-2 1Ch NG(DI33)
  // 52	Clamp down sensor-2 2Ch NG(DI37)
  // 53	Clamp down sensor-2 3Ch NG(DI41)
  // 54	Clamp down sensor-2 4Ch NG(DI45)
  // 55	Clamp down sensor-2 5Ch NG(DI49)
  ERR_LIST_CAMP_DN_SENSOR_2 = ERR_LIST_START + 53;
  // 56	Clamp down sensor-2 6Ch NG(DI53)
  // 57	Clamp down sensor-2 7Ch NG(DI57)
  // 58	Clamp down sensor-2 8Ch NG(DI61)
  // 59	pogo up sensor 1Ch NG(DI34)
  // 60	pogo up sensor 2Ch NG(DI38)
  // 61	pogo up sensor 3Ch NG(DI42)
  // 62	pogo up sensor 4Ch NG(DI46)
  // 63	pogo up sensor 5Ch NG(DI50)
  ERR_LIST_POGO_UP_SENSOR = ERR_LIST_START + 61;
  // 64	pogo up sensor 6Ch NG(DI54)
  // 65	pogo up sensor 7Ch NG(DI58)
  // 66	pogo up sensor 8Ch NG(DI62)
  // 67	pogo down sensor 1Ch NG(DI34)
  // 68	pogo down sensor 2Ch NG(DI38)
  // 69	pogo down sensor 3Ch NG(DI42)
  // 70	pogo down sensor 4Ch NG(DI46)
  // 71	pogo down sensor 5Ch NG(DI50)
  ERR_LIST_POGO_DN_SENSOR = ERR_LIST_START + 69;
  // 72	pogo down sensor 6Ch NG(DI54)
  // 73	pogo down sensor 7Ch NG(DI58)
  // 74	pogo down sensor 8Ch NG(DI62)
  // 75	Carrier detect sensor 1Ch NG(DI35)
  // 76	Carrier detect sensor 2Ch NG(DI39)
  // 77	Carrier detect sensor 3Ch NG(DI43)
  // 78	Carrier detect sensor 4Ch NG(DI47)
  // 79	Carrier detect sensor 5Ch NG(DI51)
  ERR_LIST_CARRIER_DETECT_SENSOR = ERR_LIST_START + 77;
  // 80	Carrier detect sensor 6Ch NG(DI55)
  // 81	Carrier detect sensor 7Ch NG(DI59)
  // 82	Carrier detect sensor 8Ch NG(DI63)
  ERR_LIST_MORTOR_STOP_SENSOR = ERR_LIST_START + 86;

  ERR_LIST_STEP_MOTOR_DISCONNECTED = ERR_LIST_START + 90;
  ERR_LIST_STEP_MOTOR_POSITION_NG = ERR_LIST_STEP_MOTOR_DISCONNECTED + 1;
  ERR_LIST_STEP_MOTOR_CANNOT_WORK = ERR_LIST_STEP_MOTOR_DISCONNECTED + 2;

  ERR_LIST_IONIZER_STATUS_NG = ERR_LIST_START + 100;
  ERR_LIST_CAMMERA_1_CONNECTION_NG = ERR_LIST_START + 101;
  ERR_LIST_CAMMERA_2_CONNECTION_NG = ERR_LIST_CAMMERA_1_CONNECTION_NG + 1;
  ERR_LIST_CAMMERA_3_CONNECTION_NG = ERR_LIST_CAMMERA_1_CONNECTION_NG + 2;
  ERR_LIST_CAMMERA_4_CONNECTION_NG = ERR_LIST_CAMMERA_1_CONNECTION_NG + 3;
  ERR_LIST_CAM_LAMP_CONNECT_NG = ERR_LIST_START + 105;
  ERR_LIST_ROBOT_NG = ERR_LIST_START + 106;
  ERR_LIST_ECS_NG = ERR_LIST_START + 107;
  ERR_LIST_DIO_CARD_DISCONNECTED = ERR_LIST_START + 108;
  ERR_LIST_MAX = ERR_LIST_ECS_NG + 8;

  // MAX_ALARM_DATA_SIZE = 10;
  MAX_ALARM_DATA_SIZE = ERR_LIST_MAX div 8;

implementation

end.
